# Generated by Django 5.0.3 on 2024-04-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('active', models.BooleanField()),
                ('supplier_email', models.EmailField(max_length=254)),
                ('type', models.IntegerField(choices=[(1, 'Personal Computer'), (2, 'Home Electric'), (3, 'Food')])),
                ('purchase_date', models.DateField()),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
