# Generated by Django 5.0.3 on 2024-04-24 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_pid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='products.supplier'),
        ),
    ]
